project_name: gnmic
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/karimra/gnmic/cmd.version={{.Version}} -X github.com/karimra/gnmic/cmd.commit={{.ShortCommit}} -X github.com/karimra/gnmic/cmd.date={{.Date}} -X github.com/karimra/gnmic/cmd.gitURL={{.GitURL}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    hooks:
      post: upx "{{ .Path }}"
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - gnmic
    image_templates:
      - "gnmic/gnmic:latest"
      - 'gnmic/gnmic:{{ replace .Version "v" ""}}'
    dockerfile: goreleaser.dockerfile
    skip_push: false
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
      386: i386
      arm: armv7
      arm64: aarch64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
