username: admin
password: sros
port: 57400
timeout: 5s
skip-verify: true
tls-key: /path/to/client.key
tls-cert: /path/to/client.crt

targets:
  172.17.0.100:
    username: grpc
    password: grpc
  172.17.0.101:
  172.17.0.102:57000:
    password: sros123

outputs:
  file:
    - filename: local.log
  nats:
    - address: localhost:4222
      subject: telemetry
      username:
      password:
  stan:
    - address: localhost:4222
      subject: telemetry
      username:
      password:
      name:
      clusterName:
      timeout:
      pingInterval:
      pingRetry:
  kafka:
    - address:
      topic: 
      maxRetry:
      timeout:
