username: admin
password: sros
port: 57400
timeout: 5s
skip-verify: true
tls-key: /path/to/client.key
tls-cert: /path/to/client.crt

targets:
  172.17.0.100:
    username: ""
    password: ""
    timeout: 2s
    subscriptions:
      - sub1
  172.17.0.101:
    username: sros
    password: sros
    insecure: true
    tls-key: dummy/path/file1
    tls-cert: dummy/path/file2
    subscriptions:
      - sub1
      - sub2
  172.17.0.102:57000:
    password: sros123

subscriptions:
  sub1:
    paths:
      - /configure/port[port-id=*]
      - /state
    mode: on_change # target-defined # sample
  sub2:
    paths:
       - /configure/port[port-id=*]
    mode: sample
    sample-interval: 30s

outputs:
  group1:
    - filename: local.log
      type: file
    - fileType: stdout
      type: file
  group2:
    - type: file
      filename: local.log
      
    - type: nats
      address: localhost:4222
      subjectPrefix: telemetry
      username:
      password:
    - type: file
      filename: localFile.log
  group3:
    - type: stan
      address: localhost:4223
      subject: telemetry
      username:
      password:
      name:
      clusterName:
      timeout:
      pingInterval:
      pingRetry:
  group4:
    - type: kafka
      address: localhost:9092
      topic: telemetry
      maxRetry: 
      timeout:
