site_name: gNMIc
nav:
  - Home: index.md
  - Getting started:
      - Installation: install.md
      - Basic usage: basic_usage.md
      - Global flags: global_flags.md
  - User guide:
      - Configuration:
        - Introduction: user_guide/configuration_intro.md
        - Flags: user_guide/configuration_flags.md
        - Environment variables: user_guide/configuration_env.md
        - File configuration: user_guide/configuration_file.md
      - Prompt mode and auto-suggestions: user_guide/prompt_suggestions.md
      - Targets: user_guide/targets.md
      - Target loaders: user_guide/target_loaders.md
      - Subscriptions: user_guide/subscriptions.md
      - Inputs:
        - Introduction: user_guide/inputs/input_intro.md
        - NATS: user_guide/inputs/nats_input.md
        - STAN: user_guide/inputs/stan_input.md
        - Kafka: user_guide/inputs/kafka_input.md
      - Outputs:
          - Introduction: user_guide/outputs/output_intro.md
          - File: user_guide/outputs/file_output.md
          - NATS: user_guide/outputs/nats_output.md
          - STAN: user_guide/outputs/stan_output.md
          - Kafka: user_guide/outputs/kafka_output.md
          - Prometheus:  user_guide/outputs/prometheus_output.md
          - TCP: user_guide/outputs/tcp_output.md
          - UDP: user_guide/outputs/udp_output.md
          - InfluxDB: user_guide/outputs/influxdb_output.md
      - Processors: 
          - Introduction: user_guide/event_processors/intro.md
          - Add Tag: user_guide/event_processors/event_add_tag.md
          - Convert: user_guide/event_processors/event_convert.md
          - Date string: user_guide/event_processors/event_date_string.md
          - Delete: user_guide/event_processors/event_delete.md
          - Drop: user_guide/event_processors/event_drop.md
          - JQ: user_guide/event_processors/event_jq.md
          - Merge: user_guide/event_processors/event_merge.md
          - Override TS: user_guide/event_processors/event_override_ts.md
          - Strings: user_guide/event_processors/event_strings.md
          - To Tag: user_guide/event_processors/event_to_tag.md
          - Trigger: user_guide/event_processors/event_trigger.md
          - Write: user_guide/event_processors/event_write.md
      - Clustering: user_guide/HA.md
      - API: 
          - Introduction: user_guide/api/api_intro.md
          - Configuration: user_guide/api/configuration.md
          - Targets: user_guide/api/targets.md
  
  - Deployment examples:
      - Index: deployments/deployments_intro.md
      - Single Instance: 
          - NATS output: deployments/single-instance/nats-output.md
          - Kafka output: deployments/single-instance/kafka-output.md
          - InfluxDB output: deployments/single-instance/influxdb-output.md
          - Prometheus output: deployments/single-instance/prometheus-output.md
          - Multiple outputs:  deployments/single-instance/multiple-outputs.md

      - Clusters: 
          - InfluxDB output: deployments/clusters/cluster_with_influxdb_output.md
          - Prometheus output: deployments/clusters/cluster_with_prometheus_output.md
          - Prometheus output with data replication: deployments/clusters/cluster_with_nats_input_and_prometheus_output.md

      - Pipelines:  
          - NATS to Prometheus: deployments/pipelines/nats_prometheus.md
          - NATS to InfluxDB: deployments/pipelines/nats_influxdb.md
          - Clustered pipeline: deployments/pipelines/gnmic_cluster_nats_prometheus.md
          - Forked pipeline: deployments/pipelines/forked_pipeline.md
  
  - Command reference:
      - Capabilities: cmd/capabilities.md
      - Get: cmd/get.md
      - Set: cmd/set.md
      - GetSet: cmd/getset.md
      - Subscribe: cmd/subscribe.md
      - Listen: cmd/listen.md
      - Path: cmd/path.md
      - Prompt: cmd/prompt.md

site_author: Karim Radhouani
site_description: >-
  gnmi client and collector command line interface
# Repository
repo_name: karimra/gnmic
repo_url: https://github.com/karimra/gnmic
edit_uri: ""
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    scheme: preference
    primary: blue
    accent: indigo
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: octicons/pulse-24
  favicon: images/pulse.svg

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/karimra

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

google_analytics:
  - UA-177206500-1
  - auto
