username: admin
password: admin
insecure: true
encoding: json_ietf
log: true
api: ":7892"

# clustering config
clustering:
  cluster-name: cluster1
  instance-name: gnmic3
  service-address: gnmic3
  targets-watch-timer: 5s
  locker:
    type: consul
    address: consul-agent:8500

targets:
  # Add targets configuration here
  # eg:
  # 192.168.1.131:57400:
  #   username: gnmic
  #   password: secret_password
  #   outputs:
  #     - nats-output

subscriptions:
  # Add subscriptions configuration here
  # e.g:
  # sub1:
  #   paths:
  #     - /interface/statistics
  #   stream-mode: sample
  #   sample-interval: 1s

inputs:
  nats-input:
    type: input
    address: nats:4222
    subject: telemetry
    outputs:
      - prom-output

outputs:
  nats-output:
    type: nats
    address: nats:4222
    subject: telemetry

  prom-output:
    type: prometheus
    listen: "gnmic3:9806"
    service-registration:
      address: consul-agent:8500
      use-lock: true