log: true

inputs:
  nats-input:
    type: input
    address: nats:4222
    subject: telemetry
    outputs:
      - prom-output

outputs:
  prom-output:
    type: prometheus
    listen: "gnmic-relay2:9805"
    service-registration:
      address: consul-agent:8500
      use-lock: true
