username: admin
password: admin
insecure: true
encoding: json_ietf
log: true

api: ":7891"

# clustering config
clustering:
  cluster-name: cluster1
  instance-name: gnmic-collector2
  service-address: gnmic-collector2
  targets-watch-timer: 5s
  locker:
    type: consul
    address: consul-agent:8500

targets:
  # Add targets configuration here
  # eg:
  # 192.168.1.131:57400:
  #   username: gnmic
  #   password: secret_password


subscriptions:
  # Add subscriptions configuration here
  # e.g:
  # sub1:
  #   paths:
  #     - /interface/statistics
  #   stream-mode: sample
  #   sample-interval: 1s


outputs:
  nats-output:
    type: nats
    address: nats:4222
    subject: telemetry
